### PR TITLE
Enables manila tests

### PR DESCRIPTION
**Pull request by sayalilunkad**
Enables manila tests in tempest if manila service is running.

### CODE REVIEW

**Comment by dirkmueller** [comment]
commit message says "enables", but the change actually disables Manila.. what did you intend to do ?

**Comment by sayalilunkad** [comment]
@dirkmueller I wanted to add the option to run manila tests in tempest but was not sure if it should be true by default. If so I will change it.

**Comment by dirkmueller** [comment]
@sayalilunkad well, now it will fail.. manila needs to be configured first before you can run tempest against it.

**Comment by toabctl** [comment]
Set the label because the tests will fail (as @dirkmueller mentioned in https://github.com/SUSE-Cloud/openstack-quickstart/pull/51#issuecomment-169627539 )

**Comment by toabctl** [comment]
I think we should set this to False for now. Running tempest tests for Manila in cleanvm is currently not the focus.

**Comment by toabctl** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
