### PR TITLE
Adds admin endpoint url

### PR DESCRIPTION
**Pull request by sayalilunkad**
This patch introduces variable KEYSTONE_ADMIN_ENDPOINT
and applies it where necessary.

### CODE REVIEW

**Comment by aplanas** [comment]
s/AMDIN/ADMIN/

**Comment by vuntz** [comment]
Can you remove the merge commit? (you just need to rebase)

Btw, I would just have added this in https://github.com/SUSE-Cloud/openstack-quickstart/pull/46 ;-)

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
-1

**Pull request closed without merging**
