### PR TITLE
Use qemu instead of lxc as virt_type fallback

### PR DESCRIPTION
**Pull request by toabctl**
When kvm can not be used, use qemu instead of lxc. lxc does
not work we we do not have lxc packages available.

### CODE REVIEW

**Comment by dirkmueller** [comment]
@toabctl typo in git commit message (insead instead of instead)

**Comment by toabctl** [comment]
@dirkmueller done

**Comment by aplanas** [comment]
s/intsead/instead

**Comment by toabctl** [comment]
> s/intsead/instead

fixed (finally)

**Comment by Itxaka** [comment]
Sorry :sob: 
typo on first commit message:

`` work we we do not have lxc packages available` we we -> when we

**Comment by toabctl** [comment]
@Itxaka puh. pardon. fixed

**Pull request merged**
